### ISSUE TITLE
KeyError: 'write-tree-dock' on launch

### ISSUE THREAD

**Issue by olivierkes** [jacquetc/plume-creator#2]
Hi,

Just wanted to give a try to plume-creator here (commit 2961da8632cb804871fb4c36c092a3a5d6ee388c), and see if I could contribute a little, but i'm not able to run it.
Am I doing something wrong?

Here is the trace:

Traceback (most recent call last):
  File "src/plume/plume.py", line 28, in <module>
    gui = launch_gui(core)
  File "src/plume/plume.py", line 10, in launch_gui
    gui.init_gui()
  File "/home/olivier/Documents/Travail/Geekeries/Python/plume-creator/plume-creator/src/plume/gui/gui.py", line 24, in init_gui
    self.window = MainWindow(self)
  File "/home/olivier/Documents/Travail/Geekeries/Python/plume-creator/plume-creator/src/plume/gui/main_window.py", line 23, in __init__
    self.init_ui()
  File "/home/olivier/Documents/Travail/Geekeries/Python/plume-creator/plume-creator/src/plume/gui/main_window.py", line 60, in init_ui
    self.write_sub_window = WritePanel(parent=self, parent_window_system_controller=self \
  File "/home/olivier/Documents/Travail/Geekeries/Python/plume-creator/plume-creator/src/plume/gui/sub_window.py", line 58, in __init__
    self.dock_system.add_dock("write-tree-dock",  Qt.LeftDockWidgetArea)
  File "/home/olivier/Documents/Travail/Geekeries/Python/plume-creator/plume-creator/src/plume/gui/docks.py", line 58, in add_dock
    self.change_type(dock, type_str)
  File "/home/olivier/Documents/Travail/Geekeries/Python/plume-creator/plume-creator/src/plume/gui/docks.py", line 69, in change_type
    gui_part = self.dock_type_dict[type_str]
KeyError: 'write-tree-dock'

**Comment by olivierkes** [comment]
OK sorry, just had to run plume.py from src/plume.
:)
